# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugz', '0003_auto_20171113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reason',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
